### PR TITLE
update to how to import projects to eclipse section as previous metho…

### PR DESCRIPTION
**Pull request by samredway**
…d was tricky and more time consuming

### CODE REVIEW

**Comment by samredway** [comment]
Suggesting this approach in response to this conversation:

https://groups.google.com/forum/#!topic/openworm-discuss/535GU_7d590

This is my first pull request so please let me know if there is something I have done wrong or in a non-standard manor. 

Thank You

Sam

**Comment by gidili** [comment]
@samredway thanks! Only thing I'd suggest before we merge it in is to leave the old stuff as well, keeping the two as alternate solutions

**Comment by samredway** [comment]
Yes I had thought that might be the best way, I will do that now

**Comment by samredway** [comment]
I think that is it. Let me know if there is anything else I can do.

**Comment by gidili** [comment]
@samredway cool thanks! I am curious to know how you fixed the opencl drivers issue and if it's worth documenting too

**Comment by samredway** [comment]
Hi, embarrassingly that issue with the openCL was just a me problem. I had downloaded the latest Beta of AMDAPPSDK, which did't work with the instructions, and set my environment variables incorrectly. So the solution was just to go back and download the latest stable version (2.9) and reset my environment variables correctly, and follow the instructions in the docs provided. So in that case the docs were actually spot on :/

**Comment by gidili** [comment]
@samredway good - happy ending then! :)

**Pull request merged**
