### PR TITLE
Update build.rst

### PR DESCRIPTION
**Pull request by adrianq**
New build process: GeppettoConfiguration and mvn

### CODE REVIEW

**Comment by tarelli** [comment]
@gidili can you review?

**Comment by gidili** [comment]
Very good 👍 seal of approval 
seal

**Comment by adrianq** [comment]
@gidili Thanks for the changes! and for the seal of approval... a dream of a lifetime!

**Comment by gidili** [comment]
@adrianq making your wildest dreams come true 💯

**Pull request merged**
